name: Distribute ABAP (Demo)
on:
  release:
    types: [ published ]
env:
  SYSTEM_NAME: #System (RFC/BTP Proxy)
  TARGET_SYSTEM: #TMS: System Name
  REPO_DIR_NAME: regrepo #HIDDEN Nome directory
  TEMPLATE: demodistribute #HIDDEN Elimina questa variabile se si vogliono mantenere modifiche a job a fronte di update al template
jobs:
  checkout:
    name: Checkout
    runs-on: ubuntu-latest
    outputs:
      versionCheck: ${{ steps.versionCheck.outputs.res }}
    steps:
      - name: Checkout RegRepo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          path: ${{ env.REPO_DIR_NAME }}
      - name: Checkout Regesta Actions
        uses: actions/checkout@v2
        with:
          repository: RegestaItalia/actions
          token: ${{ secrets.CI_GITHUB_TOKEN }}
          path: actions/regesta
      - name: Zip artifact checkout
        run: zip checkout.zip ./* -r
      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: checkout
          path: checkout.zip
          retention-days: 1
  envToOutput:
    name: Env To Output
    runs-on: ubuntu-latest
    needs: checkout
    outputs:
      vars: ${{ steps.envtooutput.outputs.vars }}
    steps:
      - uses: actions/download-artifact@master
        with:
          name: checkout
          path: ./
      - name: Unzip checkout
        run: unzip checkout.zip
      - name: Env To Output
        id: envtooutput
        uses: ./actions/regesta/envToOutput
        with:
          yamlFilePath: ./${{ env.REPO_DIR_NAME }}/.github/workflows/regrepo.yml
  readDotRegrepo:
    name: Read .regrepo
    runs-on: ubuntu-latest
    needs: checkout
    outputs:
      vars: ${{ steps.dotregrepo.outputs.vars }}
    steps:
      - uses: actions/download-artifact@master
        with:
          name: checkout
          path: ./
      - name: Unzip checkout
        run: unzip checkout.zip
      - name: Read .regrepo
        id: dotregrepo
        uses: ./actions/regesta/regGit/readDotRegRepo
        with:
          filePath: ./${{ env.REPO_DIR_NAME }}/.regrepo/.regrepo.xml
  distributeRelease:
    name: Distribute release
    runs-on: ubuntu-latest
    needs: [ envToOutput, readDotRegrepo ]
    steps:
      - uses: actions/download-artifact@master
        with:
          name: checkout
          path: ./
      - name: Unzip checkout
        run: unzip checkout.zip
      - name: Distribute
        id: distribute
        uses: ./actions/regesta/regGit/distributeRegRepoRelease
        with:
          username: ${{ secrets.RST_USER }}
          password: ${{ secrets.RST_PASSWORD }}
          artifactId: ${{ fromJson(needs.readDotRegrepo.outputs.vars).ARTIFACT }}
          tag: ${{ fromJson(github.event).release.tag_name }}
          systemName: ${{ fromJson(needs.envToOutput.outputs.vars).SYSTEM_NAME }}
          systemTarget: ${{ fromJson(needs.envToOutput.outputs.vars).TARGET_SYSTEM }}
