name: Fiori

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
    types: [closed]
env:
  WKF_UIVERI5_TESTS: false #Esegui test UiVeri5
  WKF_DEPLOY: true #Effettua deploy su OnPremise ABAP
  APPDIR: app #OPTIONAL Nome directory applicazione
jobs:
  firstRelease:
    name: First release
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Is from pull request?
        uses: 8BitJonny/gh-get-current-pr@1.2.0
        id: PR
        with:
          github-token: ${{ secrets.CI_GITHUB_TOKEN }}
      - name: Checkout app Fiori
        if: steps.PR.outputs.number == ''
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          path: ${{ env.APPDIR }}
      - name: Import Regesta Actions
        if: steps.PR.outputs.number == ''
        uses: actions/checkout@v2
        with:
          repository: RegestaItalia/actions
          token: ${{ secrets.CI_GITHUB_TOKEN }}
          path: actions/regesta
      - name: Confronto versioni
        if: steps.PR.outputs.number == ''
        id: check
        uses: ./actions/regesta/versionCheck
        with:
          localPackagePath: './${{ env.APPDIR }}/package.json'
          githubToken: ${{ secrets.CI_GITHUB_TOKEN }}
          repository: ${{ github.repository }}
      - name: Crea nuova release
        uses: ncipollo/release-action@v1
        if: steps.check.outputs.compare == 1 && steps.PR.outputs.number == ''
        with:
          body: First release - v${{ steps.check.outputs.localVersion }}
          tag: ${{ steps.check.outputs.localVersion }}
          token: ${{ secrets.CI_GITHUB_TOKEN }}
          commit: ${{ github.sha }}
  buildDeploy:
    name: Build e deploy RST
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout app Fiori
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          path: ${{ env.APPDIR }}
      - name: Import Regesta Actions
        uses: actions/checkout@v2
        with:
          repository: RegestaItalia/actions
          token: ${{ secrets.CI_GITHUB_TOKEN }}
          path: actions/regesta
      - name: Import registry Regesta
        uses: ./actions/regesta/regestaRegistry
        with:
          path: ./${{ env.APPDIR }}/.npmrc
          token: ${{ secrets.CI_GITHUB_TOKEN }}
      - name: Confronto versioni
        id: check
        uses: ./actions/regesta/versionCheck
        with:
          localPackagePath: './${{ env.APPDIR }}/package.json'
          githubToken: ${{ secrets.CI_GITHUB_TOKEN }}
          repository: ${{ github.repository }}
      - run: npm ci
        if: steps.check.outputs.compare == 1
        working-directory: ./${{ env.APPDIR }}
      - name: Esecuzione test UiVeri5
        if: steps.check.outputs.compare == 1 && env.WKF_UIVERI5_TESTS == true
        uses: ./actions/regesta/uiveri5
        with:
          repoName: ${{ github.repository }}
          runId: ${{ github.run_id }}
          githubToken: ${{ secrets.CI_GITHUB_TOKEN }}
          appDir: ${{ env.APPDIR }}
      - name: Build
        if: steps.check.outputs.compare == 1 && env.WKF_DEPLOY == true
        run: npm run build
        working-directory: ./${{ env.APPDIR }}
      - name: Deploy
        if: steps.check.outputs.compare == 1 && env.WKF_DEPLOY == true
        run: npx fiori deploy -u ${{ secrets.RST_ENDPOINT }} --username RST_USR --password RST_PWD -l ${{ secrets.RST_CLIENT }} -y -f 
        working-directory: ./${{ env.APPDIR }}
        env:
          RST_USR: ${{ secrets.RST_USR }}
          RST_PWD: ${{ secrets.RST_PWD }}
      - name: Info Pull Request
        if: steps.check.outputs.compare == 1
        uses: 8BitJonny/gh-get-current-pr@1.2.0
        id: PR
        with:
          github-token: ${{ secrets.CI_GITHUB_TOKEN }}
          sha: ${{ github.event.pull_request.head.sha }}
      - name: Crea nuova release
        uses: ncipollo/release-action@v1
        if: steps.check.outputs.compare == 1
        with:
          body: ${{ steps.PR.outputs.pr_body }}
          tag: ${{ steps.check.outputs.localVersion }}
          token: ${{ secrets.CI_GITHUB_TOKEN }}
          commit: ${{ github.sha }}
