name: RegGit Changelog
on:
  issues:
    types: [ closed ]
env:
  REPO_DIR_NAME: regrepo #HIDDEN Nome directory
jobs:
  checkout:
    name: Checkout
    runs-on: ubuntu-latest
    steps:
      - name: Checkout RegRepo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          path: ${{ env.REPO_DIR_NAME }}
      - name: Checkout Regesta Actions
        uses: actions/checkout@v2
        with:
          repository: RegestaItalia/actions
          token: ${{ secrets.CI_GITHUB_TOKEN }}
          path: actions/regesta
      - name: Zip artifact checkout
        run: zip checkout.zip ./* -r
      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: checkout
          path: checkout.zip
          retention-days: 1
  updateChangelog:
    name: Update changelog
    runs-on: ubuntu-latest
    needs: [ checkout ]
    steps:
      - uses: actions/download-artifact@master
        with:
          name: checkout
          path: ./
      - name: Unzip checkout
        run: unzip checkout.zip
      - name: update changelog
        uses: ./actions/regesta/regGit/updateChangelog
        with:
          repoPath: /${{ env.REPO_DIR_NAME }}
          artifact: ${{ github.event.repository.name }}
          githubToken: ${{ secrets.CI_GITHUB_TOKEN }}
          issueNumber: ${{ github.event.issue.number }}
  alignAfterPr:
    name: Align after PR
    runs-on: ubuntu-latest
    needs: updateChangelog
    steps:
      - uses: actions/download-artifact@master
        with:
          name: checkout
          path: ./
      - name: Unzip checkout
        run: unzip checkout.zip
      - name: Align after PR
        uses: ./actions/regesta/alignAfterPr
        with:
          githubToken: ${{ secrets.CI_GITHUB_TOKEN }}
          repoName: ${{ github.event.repository.name }}
