name: RegRepo
on:
  push:
    branches: [ $default-branch ]
env:
  REPO_DIR_NAME: regrepo #HIDDEN Nome directory
  TEMPLATE: regrepo #HIDDEN Elimina questa variabile se si vogliono mantenere modifiche a job a fronte di update al template
jobs:
  checkout:
    name: Checkout
    runs-on: ubuntu-latest
    outputs:
      versionCheck: ${{ steps.versionCheck.outputs.res }}
    steps:
      - name: Checkout RegRepo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          path: ${{ env.REPO_DIR_NAME }}
      - name: Checkout Regesta Actions
        uses: actions/checkout@v2
        with:
          repository: RegestaItalia/actions
          token: ${{ secrets.CI_GITHUB_TOKEN }}
          path: actions/regesta
      - name: Zip artifact checkout
        run: zip checkout.zip ./* -r
      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: checkout
          path: checkout.zip
          retention-days: 1
  alignAfterPr:
    name: Align after PR
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - uses: actions/download-artifact@master
        with:
          name: checkout
          path: ./
      - name: Unzip checkout
        run: unzip checkout.zip
      - name: Align after PR
        uses: ./actions/regesta/alignAfterPr
        with:
          githubToken: ${{ secrets.CI_GITHUB_TOKEN }}
          repoName: ${{ github.event.repository.name }}
