name: RegRepo
on:
  push:
    branches: [ $default-branch ]
env:
  REPO_DIR_NAME: regrepo #HIDDEN Nome directory
  TEMPLATE: regrepo #HIDDEN Elimina questa variabile se si vogliono mantenere modifiche a job a fronte di update al template
jobs:
  checkPullRequest:
    name: Check Pull Request
    runs-on: ubuntu-latest
    outputs:
      body: ${{ steps.findPr.outputs.body }}
    steps:
     - name: Trova PR
       uses: actions-ecosystem/action-get-merged-pull-request@main
       id: findPr
       with:
        github_token: ${{ secrets.CI_GITHUB_TOKEN }}
  checkout:
    name: Checkout
    needs: [ checkPullRequest ]
    runs-on: ubuntu-latest
    outputs:
      versionCheck: ${{ steps.versionCheck.outputs.res }}
    steps:
      - name: Checkout RegRepo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          path: ${{ env.REPO_DIR_NAME }}
      - name: Checkout Regesta Actions
        uses: actions/checkout@v2
        with:
          repository: RegestaItalia/actions
          token: ${{ secrets.CI_GITHUB_TOKEN }}
          path: actions/regesta
      - name: Confronto versioni
        id: versionCheck
        uses: ./actions/regesta/versionCheck
        with:
          localApackPath: ./${{ env.REPO_DIR_NAME }}/.apack-manifest.xml
          githubToken: ${{ secrets.CI_GITHUB_TOKEN }}
          repository: ${{ github.repository }}
      - name: Check incremento versione
        if: steps.versionCheck.outputs.compare < 1
        uses: actions/github-script@v3
        with:
          script: |
              core.setFailed('Crea nuova versione! Expected current version ${{ steps.versionCheck.outputs.localVersion }} to be greater then latest available version, ${{ steps.versionCheck.outputs.remoteVersion }}')
      - name: Zip artifact checkout
        run: zip checkout.zip ./* -r
      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: checkout
          path: checkout.zip
          retention-days: 1
  envToOutput:
    name: Env To Output
    runs-on: ubuntu-latest
    needs: checkout
    outputs:
      vars: ${{ steps.envtooutput.outputs.vars }}
    steps:
      - uses: actions/download-artifact@master
        with:
          name: checkout
          path: ./
      - name: Unzip checkout
        run: unzip checkout.zip
      - name: Env To Output
        id: envtooutput
        uses: ./actions/regesta/envToOutput
        with:
          yamlFilePath: ./${{ env.REPO_DIR_NAME }}/.github/workflows/regrepo.yml
  readDotRegrepo:
    name: Read .regrepo
    runs-on: ubuntu-latest
    needs: checkout
    outputs:
      vars: ${{ steps.dotregrepo.outputs.vars }}
    steps:
      - uses: actions/download-artifact@master
        with:
          name: checkout
          path: ./
      - name: Unzip checkout
        run: unzip checkout.zip
      - name: Read .regrepo
        id: dotregrepo
        uses: ./actions/regesta/regGit/readDotRegRepo
        with:
          filePath: ./${{ env.REPO_DIR_NAME }}/.regrepo/.regrepo.xml
  createRelease:
    name: Create release
    runs-on: ubuntu-latest
    needs: [ checkPullRequest, checkout, envToOutput, readDotRegrepo ]
    if: ${{ fromJson(needs.checkout.outputs.versionCheck).compare == 1 }}
    steps:
      - uses: actions/download-artifact@master
        with:
          name: checkout
          path: ./
      - name: Unzip checkout
        run: unzip checkout.zip
      - name: Crea transport
        id: generateRelease
        uses: ./actions/regesta/regGit/generateRegRepoRelease
        with:
          releasePath: ./${{ env.REPO_DIR_NAME }}
          username: ${{ secrets.RST_USER }}
          password: ${{ secrets.RST_PASSWORD }}
          artifactId: ${{ fromJson(needs.readDotRegrepo.outputs.vars).ARTIFACT }}
          package: ${{ fromJson(needs.readDotRegrepo.outputs.vars).MAIN_PACKAGE.ORIGINAL_PACKAGE_NAME }}
          version: ${{ fromJson(needs.checkout.outputs.versionCheck).localVersion }}
      - name: Crea release
        uses: ncipollo/release-action@v1
        with:
          body: v${{ fromJson(needs.checkout.outputs.versionCheck).localVersion }}\n${{ needs.checkPullRequest.outputs.body }}
          tag: ${{ fromJson(needs.checkout.outputs.versionCheck).localVersion }}
          token: ${{ secrets.CI_GITHUB_TOKEN }}
          commit: ${{ github.sha }}
          artifacts: ${{ steps.generateRelease.outputs.releasePath }}
