name: Sample CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
env:
  VAR_BOOL: true #Variabile boolean
  VAR_STR1: esempio #Variabile string 1
  VAR_STR2: 'esempio' #Variabile string 2
  VAR_NUMB: 10 #Variabile numero
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello from Sample CI
