name: Install ABAP release
on:
    workflow_call:
      inputs:
        systemId:
          required: true
          type: string
        client:
          required: true
          type: string
        username:
          required: true
          type: string
        registryEndpoint:
          required: true
          type: string
        dest:
          required: true
          type: string
        asHost:
          required: true
          type: string
        sysNr:
          required: true
          type: string
        sapRouter:
          required: false
          type: string
        lang:
          required: true
          type: string
        importTimeout:
          required: false
          type: string
        wbTransportTarget:
          required: true
          type: string
        packageVersion:
          required: true
          type: string
jobs:
  checkout:
    name: Checkout
    runs-on: ubuntu-latest
    steps:
      - name: Checkout RegRepo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          path: repo
      - name: Checkout Regesta Actions
        uses: actions/checkout@v2
        with:
          repository: RegestaItalia/actions
          token: ${{ secrets.CI_GITHUB_TOKEN }}
          path: actions/regesta
      - name: Zip artifact checkout
        run: zip checkout.zip ./* -r
      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: checkout_release
          path: checkout.zip
          retention-days: 1
  trmPublish:
    name: TRM Install
    needs: checkout
    runs-on: [self-hosted, Windows, RegRunner]
    steps:
      - uses: actions/download-artifact@master
        with:
          name: checkout_release
          path: ./
      - name: Unzip checkout
        run: tar -xf checkout.zip
        shell: cmd
      - name: TRM Install
        uses: ./actions/regesta/booster/installTrm
        with:
          endpoint: ${{ inputs.stagingRegistryEndpoint }}
          token: ${{ secrets.TRM_TOKEN }}
          dest: ${{ inputs.dest }}
          asHost: ${{ inputs.asHost }}
          sysNr: ${{ inputs.sysNr }}
          sapRouter: ${{ inputs.sapRouter }}
          client: ${{ inputs.client }}
          lang: ${{ inputs.lang }}
          user: ${{ inputs.username }}
          password: ${{ secrets[format('{0}_PASSWORD', inputs.systemId)] }}
          manifestPath: ./repo/manifest.json
          packageVersion: ${{ inputs.packageVersion }}
          wbTransportTarget: ${{ inputs.wbTransportTarget }}
          importTimeout: ${{ inputs.importTimeout }}
