name: Install ABAP release
on:
    workflow_call:
      inputs:
        systemId:
          required: true
          type: string
        client:
          required: true
          type: string
        username:
          required: true
          type: string
        registryEndpoint:
          required: true
          type: string
        dest:
          required: true
          type: string
        asHost:
          required: true
          type: string
        sysNr:
          required: true
          type: string
        sapRouter:
          required: false
          type: string
        lang:
          required: true
          type: string
        importTimeout:
          required: false
          type: string
        wbTransportTarget:
          required: true
          type: string
        packageVersion:
          required: true
          type: string
jobs:
  trmPublish:
    name: TRM Install
    runs-on: [self-hosted, Windows, RegRunner]
    steps:
      - uses: actions/download-artifact@master
        with:
          name: checkout
          path: ./
      - name: Unzip checkout
        run: tar -xf checkout.zip
        shell: cmd
      - name: TRM Install
        uses: ./actions/regesta/booster/installTrm
        with:
          endpoint: ${{ inputs.registryEndpoint }}
          token: ${{ secrets.TRM_TOKEN }}
          dest: ${{ inputs.dest }}
          asHost: ${{ inputs.asHost }}
          sysNr: ${{ inputs.sysNr }}
          sapRouter: ${{ inputs.sapRouter }}
          client: ${{ inputs.client }}
          lang: ${{ inputs.lang }}
          user: ${{ inputs.username }}
          password: ${{ secrets[format('{0}_PASSWORD', inputs.systemId)] }}
          manifestPath: ./repo/manifest.json
          packageVersion: ${{ inputs.packageVersion }}
          wbTransportTarget: ${{ inputs.wbTransportTarget }}
          importTimeout: ${{ inputs.importTimeout }}
