name: Get repository manifest values
on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
      ref:
        required: true
        type: string
    secrets:
      CI_GITHUB_TOKEN:
        required: true
    outputs:
      packageName:
        description: "Package name"
        value: ${{ jobs.extractManifest.outputs.packageName }}
      packageVersion:
        description: "Package version"
        value: ${{ jobs.extractManifest.outputs.packageVersion }}
      prVersion:
        description: "Package PullRequest version"
        value: ${{ jobs.extractManifest.outputs.prVersion }}
      description:
        description: "Package description"
        value: ${{ jobs.extractManifest.outputs.description }}
      keywords:
        description: "Package keywords"
        value: ${{ jobs.extractManifest.outputs.keywords }}
      backwardsCompatible:
        description: "Package backwardsCompatible"
        value: ${{ jobs.extractManifest.outputs.backwardsCompatible }}
      sapEntries:
        description: "Package sapEntries"
        value: ${{ jobs.extractManifest.outputs.sapEntries }}
      dependencies:
        description: "Package dependencies"
        value: ${{ jobs.extractManifest.outputs.dependencies }}
jobs:
  checkout:
    name: Checkout
    runs-on: ubuntu-latest
    steps:
      - name: Checkout RegRepo
        uses: actions/checkout@v2
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.ref }}
          path: repo
      - name: Checkout Regesta Actions
        uses: actions/checkout@v2
        with:
          repository: RegestaItalia/actions
          token: ${{ secrets.CI_GITHUB_TOKEN }}
          path: actions/regesta
      - name: Zip artifact checkout
        run: zip checkout.zip ./* -r
      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: checkout
          path: checkout.zip
          retention-days: 1
  extractManifest:
    name: Extract manifest values
    runs-on: [self-hosted, RegRunner]
    needs: checkout
    outputs:
      packageName: ${{ steps.manifestValues.outputs.packageName }}
      packageVersion: ${{ steps.manifestValues.outputs.packageVersion }}
      prVersion: ${{ steps.manifestValues.outputs.prVersion }}
      description: ${{ steps.manifestValues.outputs.description }}
      keywords: ${{ steps.manifestValues.outputs.keywords }}
      backwardsCompatible: ${{ steps.manifestValues.outputs.backwardsCompatible }}
      sapEntries: ${{ steps.manifestValues.outputs.sapEntries }}
      dependencies: ${{ steps.manifestValues.outputs.dependencies }}
    steps:
      - uses: actions/download-artifact@master
        with:
          name: checkout
          path: ./
      - name: Unzip checkout
        run: tar -xf checkout.zip
        shell: cmd
      - name: Extract manifest values
        id: manifestValues
        uses: ./actions/regesta/booster/readManifest
        with:
          manifestPath: './repo/manifest.json'