name: Move to release
on:
  workflow_call:
    inputs:
      registry:
        required: false
        type: string
      username:
        required: false
        type: string
jobs:
  addTags:
    name: Add tags to docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@master
        with:
          name: checkout
          path: ./
      - name: Unzip checkout
        run: unzip checkout.zip
      - name: Set registry
        run: |
          echo "DOCKER_REGISTRY=${{ inputs.registry || 'ghcr.io' }}" >> $GITHUB_ENV
      - name: Set username
        run: |
          echo "DOCKER_USERNAME=${{ inputs.username || github.actor }}" >> $GITHUB_ENV
      - name: Set password
        run: |
          echo "DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD || secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
      - name: Extract version from manifest.json
        uses: sergeysova/jq-action@v2
        id: version
        with:
          cmd: 'jq .version ./repo/manifest.json -r'
      - name: Extract image name from manifest.json
        uses: sergeysova/jq-action@v2
        id: imageName
        with:
          cmd: 'jq .name ./repo/manifest.json -r'
      - name: Change case for image name
        id: change-case
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ steps.imageName.outputs.value }}
      - name: Replace dots in image name
        uses: frabert/replace-string-action@v2.4
        with:
          pattern: \.
          string: ${{ steps.change-case.outputs.lowercase }}
          replace-with: "-"
      - name: Replace dots in image name
        uses: frabert/replace-string-action@v2.4
        with:
          pattern: \@
          string: ${{ steps.change-case.outputs.lowercase }}
          replace-with: ""
      - run: echo "image name ${{ steps.change-case.outputs.lowercase }}"
      - run: echo "pre-release version ${{ steps.version.outputs.value }}"
      - run: docker pull ${{ env.DOCKER_REGISTRY }}/${{ steps.change-case.outputs.lowercase }}:${{ steps.version.outputs.value }}
      - run: docker tag ${{ env.DOCKER_REGISTRY }}/${{ steps.change-case.outputs.lowercase }}:${{ steps.version.outputs.value }} ${{ env.DOCKER_REGISTRY }}/${{ steps.change-case.outputs.lowercase }}:latest
      - run: docker push ${{ env.DOCKER_REGISTRY }}/${{ steps.change-case.outputs.lowercase }}:latest
