name: Move to release
on:
  workflow_call:
    inputs:
      registry:
        required: true
        type: string
      username:
        required: false
        type: string
jobs:
  addTags:
    name: Add tags to docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@master
        with:
          name: checkout
          path: ./
      - name: Unzip checkout
        run: unzip checkout.zip
      - name: Extract version from manifest.json
        uses: sergeysova/jq-action@v2
        id: version
        with:
          cmd: 'jq .version ${{ inputs.manifestPath }} -r'
      - name: Extract image name from manifest.json
        uses: sergeysova/jq-action@v2
        id: imageName
        with:
          cmd: 'jq .name ${{ inputs.manifestPath }} -r'
      - name: Change case for image name
        id: change-case
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ steps.imageName.outputs.value }}
      - name: Replace dots in image name
        uses: frabert/replace-string-action@v2.4
        with:
          pattern: \.
          string: ${{ steps.change-case.outputs.lowercase }}
          replace-with: "-"
      - name: Replace dots in image name
        uses: frabert/replace-string-action@v2.4
        with:
          pattern: \@
          string: ${{ steps.change-case.outputs.lowercase }}
          replace-with: ""
      - run: echo "image name ${{ steps.change-case.outputs.lowercase }}"
      - run: echo "pre-release version ${{ steps.version.outputs.value }}"
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ inputs.registry }}
          username: ${{ inputs.username }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker pull ${{ steps.change-case.outputs.lowercase }}:${{ steps.version.outputs.value }}
      - run: docker tag ${{ steps.change-case.outputs.lowercase }}:${{ steps.version.outputs.value }} ${{ steps.change-case.outputs.lowercase }}:latest
      - run: docker push ${{ steps.change-case.outputs.lowercase }}:latest
