name: Create pre-release
on:
    workflow_call:
      inputs:
        registry:
          required: true
          type: string
        username:
          required: true
          type: string
        imageName:
          required: true
          type: string
jobs:
  createPreRelease:
    name: Create Github pre-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@master
        with:
          name: checkout
          path: ./
      - name: Unzip checkout
        run: unzip checkout.zip
      
      - name: Log in to the Container registry
        uses: docker/login-action@latest
        with:
          registry: ${{ inputs.registry }}
          username: ${{ inputs.username }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: npm install
        working-directory: repo
      - run: npm run build
        working-directory: repo
      - run: npm run build
        working-directory: repo
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@latest
        with:
          images: ${{ inputs.registry }}/${{ inputs.imageName }}
      - run: echo ${{ steps.meta.outputs.tags }}
      - run: echo ${{ steps.meta.outputs.labels }}
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@latest
        with:
          context: repo
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ inputs.registry }}/${{ inputs.imageName }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
      - name: Create pre-release
        uses: ./actions/regesta/booster/createPreRelease
        id: createPreRelease
        with:
          manifestPath: ./repo/manifest.json
