name: Create pre-release
on:
    workflow_call:
      inputs:
        registry:
          required: true
          type: string
        username:
          required: true
          type: string
        repoUrl:
          required: false
          type: string
jobs:
  buildPublishDocker:
    name: Build and publish docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@master
        with:
          name: checkout
          path: ./
      - name: Unzip checkout
        run: unzip checkout.zip
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ inputs.registry }}
          username: ${{ inputs.username }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract version from manifest.json
        uses: sergeysova/jq-action@v2
        id: version
        with:
          cmd: 'jq .version ${{ inputs.manifestPath }} -r'
      - name: Extract image name from manifest.json
        uses: sergeysova/jq-action@v2
        id: imageName
        with:
          cmd: 'jq .name ${{ inputs.manifestPath }} -r'
      - run: echo "image name ${{ steps.imageName.outputs.value }}"
      - run: echo "pre-release version ${{ steps.version.outputs.value }}"
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: repo
          push: true
          tags: |
              ${{ inputs.registry }}/${{ steps.imageName.outputs.value }}:prerelease
              ${{ inputs.registry }}/${{ steps.imageName.outputs.value }}:${{ steps.version.outputs.value }}
          labels: org.opencontainers.image.source=${{ inputs.repoUrl }}
  createPreRelease:
    name: Create Github pre-release
    runs-on: ubuntu-latest
    needs: buildPublishDocker
    steps:
      - uses: actions/download-artifact@master
        with:
          name: checkout
          path: ./
      - name: Unzip checkout
        run: unzip checkout.zip
      - name: Create pre-release
        uses: ./actions/regesta/booster/createPreRelease
        id: createPreRelease
        with:
          manifestPath: ./repo/manifest.json
