name: Create pre-release
on:
    workflow_call:
      inputs:
        registry:
          required: true
          type: string
        username:
          required: true
          type: string
        imageName:
          required: true
          type: string
        repoUrl:
          required: false
          type: string
jobs:
  createPreRelease:
    name: Create Github pre-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@master
        with:
          name: checkout
          path: ./
      - name: Unzip checkout
        run: unzip checkout.zip
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ inputs.registry }}
          username: ${{ inputs.username }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ inputs.registry }}/${{ inputs.imageName }}
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: repo
          push: true
          tags: ${{ inputs.registry }}/${{ inputs.imageName }}:latest
          labels: org.opencontainers.image.source=${{ inputs.repoUrl }}
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ inputs.registry }}/${{ inputs.imageName }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
      - name: Create pre-release
        uses: ./actions/regesta/booster/createPreRelease
        id: createPreRelease
        with:
          manifestPath: ./repo/manifest.json
